// <auto-generated />
using System;
using DesarrolloSocialModelo.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesarrolloSocialModelo.Migrations
{
    [DbContext(typeof(MyAppContext))]
    partial class MyAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.5.22302.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DesarrolloSocialModelo.DataModel.RespuestasDeFormulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(5);

                    b.Property<string>("ConQueFRecuenciaTeHacesUnChequeoMedico")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(7);

                    b.Property<string>("CorreoElectronioco")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("MarcaTemporal")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(2);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(4);

                    b.Property<string>("NummeroIdentificacion")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("PadecesDeAlgunaEnfermedadActualmente")
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnOrder(8);

                    b.Property<string>("TienesAlgunaEnfermedadOCondicionHederitaria")
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnOrder(9);

                    b.Property<string>("TienesLasVacunasContraElCovid19")
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.ToTable("RespuestasDeFormulario");
                });
#pragma warning restore 612, 618
        }
    }
}
